--ROL USUARIO--

CREATE ROLE USUARIO;

-- Permisos sobre las tablas
GRANT SELECT, INSERT ON Usuario TO USUARIO;
GRANT UPDATE ON Usuario TO USUARIO;

GRANT SELECT, INSERT ON UsuarioPremium TO USUARIO;

GRANT SELECT, INSERT ON CuentaGratis TO USUARIO;

-- Permisos sobre los paquetes
GRANT EXECUTE ON Usuario_Package TO USUARIO;
GRANT EXECUTE ON UsuarioPremium_Package TO USUARIO;
GRANT EXECUTE ON EstadoSuscripcion_Package TO USUARIO;






--ROL ADMINISTRADOR--

CREATE ROL ADMINISTRADOR;

-- Permisos sobre las tablas
GRANT SELECT, INSERT,DELETE ON Publicidad TO ADMINISTRADOR;

GRANT SELECT, INSERT ON Liga TO ADMINISTRADOR;
GRANT UPDATE ON Liga TO ADMINISTRADOR;

GRANT SELECT, INSERT ON Partido TO ADMINISTRADOR;
GRANT UPDATE ON Partido TO ADMINISTRADOR;

GRANT SELECT,INSERT ON Estadisticas TO ADMINISTRADOR;

GRANT SELECT,INSERT ON Clasificacion TO ADMINISTRADOR;

--Permisos sobre los paquetes
GRANT EXECUTE ON Publicidad_Package TO ADMINISTRADOR;
GRANT EXECUTE ON Liga_Package TO ADMINISTRADOR;
GRANT EXECUTE ON GestionPartidos TO ADMINISTRADOR;
GRANT EXECUTE ON EstadisticasPartido_Package TO ADMINISTRADOR;
GRANT EXECUTE ON Clasificacion_Package TO ADMINISTRADOR;






--ROL GERENTE EQUIPO--

CREATE ROLE GERENTE_EQUIPO;

-- Permisos sobre las tablas
GRANT SELECT, INSERT ON CuerpoTecnico TO GERENTE_EQUIPO;
GRANT UPDATE ON CuerpoTecnico TO GERENTE_EQUIPO;
GRANT DELETE ON CuerpoTecnico TO GERENTE_EQUIPO;

GRANT SELECT, INSERT ON Jugador TO GERENTE_EQUIPO;
GRANT UPDATE ON Jugador TO GERENTE_EQUIPO;

-- Permisos sobre los paquetes
GRANT EXECUTE ON RegistroEquipo_Package TO GERENTE_EQUIPO;
GRANT EXECUTE ON CuerpoTecnico_Package TO GERENTE_EQUIPO;
GRANT EXECUTE ON Jugador_Package TO GERENTE_EQUIPO;