--XPaquetes--

DROP PACKAGE Usuario_Package;

DROP PACKAGE UsuarioPremium_Package;

DROP PACKAGE EstadoSuscripcion_Package;

DROP PACKAGE Publicidad_Package;

DROP PACKAGE Liga_Package;

DROP PACKAGE GestionPartidos;

DROP PACKAGE EstadisticasPartido_Package;

DROP PACKAGE Clasificacion_Package;

DROP PACKAGE RegistroEquipo_Package;

DROP PACKAGE CuerpoTecnico_Package;

DROP PACKAGE Jugador_Package;

--XRoles y Permisos--


--XROL--
DROP ROLE USUARIOS;

DROP ROLE ADMINISTRADORES;

DROP ROLE GERENTE_EQUIPOS;


--XPERMISOS--


-- Permisos sobre las tablas
REVOKE SELECT, INSERT ON Usuario TO USUARIOS;
REVOKE UPDATE ON Usuario TO USUARIOS;

REVOKE SELECT, INSERT ON Pago TO USUARIOS;

REVOKE SELECT, INSERT ON Gratis TO USUARIOS;

-- Permisos sobre los paquetes
REVOKE EXECUTE ON Usuario_Package TO USUARIOS;
REVOKE EXECUTE ON UsuarioPremium_Package TO USUARIOS;
REVOKE EXECUTE ON EstadoSuscripcion_Package TO USUARIOS;





-- Permisos sobre las tablas
REVOKE SELECT, INSERT,DELETE ON Publicidad TO ADMINISTRADORES;

REVOKE SELECT, INSERT ON Liga TO ADMINISTRADORES;
REVOKE UPDATE ON Liga TO ADMINISTRADORES;

REVOKE SELECT, INSERT ON Partido TO ADMINISTRADORES;
REVOKE UPDATE ON Partido TO ADMINISTRADORES;

REVOKE SELECT,INSERT ON Estadisticas TO ADMINISTRADORES;

REVOKE SELECT,INSERT ON Clasificacion TO ADMINISTRADORES;

--Permisos sobre los paquetes
REVOKE EXECUTE ON Publicidad_Package TO ADMINISTRADORES;
REVOKE EXECUTE ON Liga_Package TO ADMINISTRADORES;
REVOKE EXECUTE ON GestionPartidos TO ADMINISTRADORES;
REVOKE EXECUTE ON EstadisticasPartido_Package TO ADMINISTRADORES;
REVOKE EXECUTE ON Clasificacion_Package TO ADMINISTRADORES;




-- Permisos sobre las tablas
REVOKE SELECT, INSERT ON CuerpoTecnico TO GERENTE_EQUIPOS;
REVOKE UPDATE ON CuerpoTecnico TO GERENTE_EQUIPOS;
REVOKE DELETE ON CuerpoTecnico TO GERENTE_EQUIPOS;

REVOKE SELECT, INSERT ON Jugador TO GERENTE_EQUIPOS;
REVOKE UPDATE ON Jugador TO GERENTE_EQUIPOS;

-- Permisos sobre los paquetes
REVOKE EXECUTE ON RegistroEquipo_Package TO GERENTE_EQUIPOS;
REVOKE EXECUTE ON CuerpoTecnico_Package TO GERENTE_EQUIPOS;
REVOKE EXECUTE ON Jugador_Package TO GERENTE_EQUIPOS;
